package com.springmvc_maven;

public class CpIdChecking {
    public static void main(String[] args) {
        String test = "kpanetedu\n" +
                "cjenmcms\n" +
                "mculture\n" +
                "mecross\n" +
                "mecross_s\n" +
                "mecross_sm\n" +
                "mecrossm\n" +
                "mozzet\n" +
                "mozzet02\n" +
                "actoz\n" +
                "actozgames\n" +
                "lgcns\n" +
                "lotte\n" +
                "uracle\n" +
                "cocen\n" +
                "makepoint\n" +
                "MAKESHOP01\n" +
                "playd4\n" +
                "ssandomain\n" +
                "logii\n" +
                "HGFADM601\n" +
                "hgrtadm701\n" +
                "galaxia\n" +
                "galaxiam\n" +
                "safe182\n" +
                "kookmin\n" +
                "kookmin01\n" +
                "kookmin02\n" +
                "kookmin03\n" +
                "campmobile\n" +
                "naverFN\n" +
                "ncloud\n" +
                "naver\n" +
                "navernbp\n" +
                "BON0000007\n" +
                "KIDISMST\n" +
                "KIDISMST01\n" +
                "KIDISMST02\n" +
                "KIDISMST03\n" +
                "sbbank\n" +
                "seoulsbdc\n" +
                "AJU0000003\n" +
                "AJU0000004\n" +
                "AJU0000005\n" +
                "AJU0000006\n" +
                "AJU0000007\n" +
                "AJU0000008\n" +
                "AJU0000009\n" +
                "AJU0000010\n" +
                "WFC0000003\n" +
                "WFC0000004\n" +
                "WFC0000005\n" +
                "WFC0000006\n" +
                "WFC0000007\n" +
                "WFC0000008\n" +
                "WFC0000009\n" +
                "WFC0000010\n" +
                "WFC0000011\n" +
                "WFC0000012\n" +
                "yksso\n" +
                "ewha\n" +
                "ewha1\n" +
                "INBIZ9020\n" +
                "INBIZ9021\n" +
                "INBIZ9022\n" +
                "INBIZ9023\n" +
                "INBIZ9024\n" +
                "INBIZ9025\n" +
                "INBIZ9026\n" +
                "INBIZ9027\n" +
                "INBIZ9028\n" +
                "INBIZ9029\n" +
                "INBIZ9030\n" +
                "INBIZ9031\n" +
                "INBIZ9032\n" +
                "INBIZ9033\n" +
                "INBIZ9034\n" +
                "INBIZ9035\n" +
                "INBIZ9036\n" +
                "INBIZ9037\n" +
                "INBIZ9038\n" +
                "Ckdhc5330\n" +
                "gbnet2014\n" +
                "ndaishin38\n" +
                "nbssv27\n" +
                "only7days\n" +
                "tourbaksa\n" +
                "wemake\n" +
                "interpark\n" +
                "daumins\n" +
                "kakao\n" +
                "kakaobill\n" +
                "kakaobuy\n" +
                "kakaobank\n" +
                "kakaopage\n" +
                "kakaopage1\n" +
                "Kwebtoon\n" +
                "daum\n" +
                "kakaocorp\n" +
                "kakaopay1\n" +
                "kakaopay2\n" +
                "korbit\n" +
                "ekms21c\n" +
                "ekms22\n" +
                "HDHS000002\n" +
                "HDHS000003\n" +
                "hddfs\n" +
                "ehyundai01\n" +
                "ehyundai02\n" +
                "ehyundai03\n" +
                "ehyundai04\n" +
                "ehyundai05\n" +
                "ehyundai06\n" +
                "ehyundai07\n" +
                "ehyundai08\n" +
                "ehyundai09\n" +
                "ehyundai10\n" +
                "ehyundai11\n" +
                "ehyundai12\n" +
                "ehyundai13\n" +
                "ehyundai14\n" +
                "ehyundai15\n" +
                "ehyundai16\n" +
                "ehyundai17\n" +
                "ehyundai18\n" +
                "ehyundai19\n" +
                "HDHS000001\n" +
                "ibk1\n" +
                "ibk3\n" +
                "ibkcard\n" +
                "ibkhr\n" +
                "gobizkorea\n" +
                "sbc01\n" +
                "sbcplan\n" +
                "cnsports\n" +
                "kolon02\n" +
                "members\n" +
                "pentaon\n" +
                "hiib\n" +
                "KRA0000006\n" +
                "arkonanum\n" +
                "arkotestid\n" +
                "hrdcqnet\n" +
                "hrdkorea\n" +
                "hrdkoream\n" +
                "hrdmeister\n" +
                "hrdopenvoc\n" +
                "hrdpdms\n" +
                "hrdtqnet\n" +
                "hrdwjob\n" +
                "hrdworktv\n" +
                "mobis\n";

        String[] array = test.split("\n");
        for (int i = 0; i < test.length() - 1; i++) {
            System.out.println("OR CP_ID = '" + array[i] + "'");
        }
    }
}
